/**
 * Internal DB surface for the CLI. Re-exported through a small index so the
 * command layer never reaches into `./db/*` directly.
 */

// Moved to @polaris/shared-control-plane-db so the control-plane API and the
// CLI share one implementation of every control-plane write. Re-exported here
// unchanged, so no command file had to move with them.

// The unaudited writers. CLI commands own their own transactions and write
// their audit rows inside them; the API cannot reach these at all.

// Everything below lives in @polaris/shared-control-plane-db so the CLI and
// the control-plane API share one implementation of every control-plane
// write. Re-exported here unchanged, so no command file had to move.
export {
  ABORTABLE_CLICKHOUSE_REBUILD_JOB_STATUSES,
  type ApiKeyRow,
  AUDIT_ACTOR_SOURCES,
  AUDIT_ENVIRONMENTS,
  type AuditActorSource,
  type AuditEnvironment,
  type AuditRecordRow,
  type AuditRecordsTable,
  CLICKHOUSE_REBUILD_JOB_STATUSES,
  type ClickhouseRebuildJobRow,
  type ClickhouseRebuildJobStatus,
  type ClickhouseRebuildJobsTable,
  type CompleteReplayJobInput,
  cancelReplayJobWithAudit,
  type DestinationRow,
  type FailReplayJobInput,
  fetchAllProjects,
  fetchAllSources,
  fetchSourcesById,
  fetchSourcesByProject,
  findActivationByKey,
  findActiveIsolation,
  findApiKeyById,
  findAuditRecordById,
  findClickhouseRebuildJobById,
  findDestinationById,
  findLatestIsolationByTriple,
  findOperatorTokenAuthRowById,
  findOperatorTokenById,
  findReplayJobById,
  findTopicIsolationById,
  type InsertApiKeyInput,
  type InsertClickhouseRebuildJobInput,
  type InsertDestinationInput,
  type InsertOperatorTokenInput,
  type InsertReplayJobInput,
  type InsertTopicIsolationInput,
  isAbortableClickhouseRebuildStatus,
  isTerminalClickhouseRebuildStatus,
  isTerminalReplayStatus,
  type ListAuditRecordsFilter,
  type ListClickhouseRebuildJobsFilter,
  type ListReplayJobsFilter,
  listActivationsForProcessor,
  listActiveIsolations,
  listAllActivations,
  listAllDestinations,
  listApiKeysByProjectEnv,
  listAuditRecords,
  listClickhouseRebuildJobs,
  listDestinationsByProjectEnv,
  listOperatorTokens,
  listReplayJobs,
  type MarkReplayJobRunningInput,
  markDlqResolvedWithAudit,
  markProcessorDlqResolvedWithAudit,
  markProcessorDlqRetriedWithAudit,
  OPERATOR_TOKEN_STATUSES,
  type OperatorTokenAuthRow,
  type OperatorTokenRow,
  type OperatorTokenStatus,
  type OperatorTokensTable,
  type ProcessorActivationKey,
  type ProcessorActivationRow,
  pauseReplayJobWithAudit,
  REPLAY_JOB_MODES,
  REPLAY_JOB_STATUSES,
  REPLAY_JOB_TARGETS,
  type RecordReplayChunkProgressInput,
  type ReplayJobMode,
  type ReplayJobRow,
  type ReplayJobStatus,
  type ReplayJobsTable,
  type ReplayJobTarget,
  resumeReplayJobWithAudit,
  startReplayExecutionWithAudit,
  syncProjectsWithAudit,
  syncSourcesWithAudit,
  TERMINAL_CLICKHOUSE_REBUILD_JOB_STATUSES,
  TERMINAL_REPLAY_JOB_STATUSES,
  type TopicIsolationRow,
  type UpdateDestinationOpsInput,
} from "@polaris/shared-control-plane-db";
// The unaudited writers, still reached directly by CLI commands that own
// their own transactions. Shrinking as each one moves onto a *WithAudit
// function; the subpath goes away when the list is empty.
export {
  abortClickhouseRebuildJob,
  cancelReplayJob,
  completeReplayJob,
  type DisableProcessorActivationInput,
  deactivateIsolation,
  disableDestination,
  disableDestinationReplay,
  disableProcessorActivation,
  type EnableProcessorActivationInput,
  enableDestination,
  enableDestinationReplay,
  enableProcessorActivation,
  failReplayJob,
  type InsertAuditRecordInput,
  insertApiKey,
  insertAuditRecord,
  insertClickhouseRebuildJob,
  insertDestination,
  insertOperatorToken,
  insertProject,
  insertReplayJob,
  insertSource,
  insertTopicIsolation,
  markClickhouseRebuildJobCompleted,
  markClickhouseRebuildJobFailed,
  markClickhouseRebuildJobRunning,
  markReplayJobRunning,
  pauseReplayJob,
  recordReplayChunkProgress,
  resumeReplayJob,
  revokeApiKey,
  revokeOperatorToken,
  touchOperatorTokenLastUsedAt,
  updateDestinationOps,
  updateProject,
  updateSource,
} from "@polaris/shared-control-plane-db/unaudited";
export { type ConnectDbOptions, connectDb, type DbHandle } from "./connect.js";
export { createKyselyScopedIsolationLookup } from "./topic-isolations.js";
