/**
 * Internal DB surface for the CLI.
 *
 * Almost everything here lives in `@polaris/shared-control-plane-db`, which
 * the CLI and the control-plane API both use so that one write has one
 * implementation, one audit snapshot, and one transaction shape. This barrel
 * exists so the command layer imports from a single place rather than
 * reaching into the package's internals.
 *
 * Two things stay local: `connect.ts`, which owns the CLI's own
 * `DATABASE_URL` resolution and `ConfigError`, and the transport-facing
 * isolation lookup, which belongs to the runtime hot path rather than the
 * control plane.
 */

// ---- reads and audited mutations ---------------------------------------
export {
  ABORTABLE_CLICKHOUSE_REBUILD_JOB_STATUSES,
  type ApiKeyRow,
  AUDIT_ACTOR_SOURCES,
  AUDIT_ENVIRONMENTS,
  type AuditActorSource,
  type AuditContext,
  type AuditEnvironment,
  type AuditRecordRow,
  type AuditRecordsTable,
  abortClickhouseRebuildJobWithAudit,
  CLICKHOUSE_REBUILD_JOB_STATUSES,
  type ClickhouseRebuildJobRow,
  type ClickhouseRebuildJobStatus,
  type ClickhouseRebuildJobsTable,
  type CompleteReplayJobInput,
  cancelReplayJobWithAudit,
  createApiKeyWithAudit,
  createClickhouseRebuildJobWithAudit,
  createDestinationWithAudit,
  createOperatorTokenWithAudit,
  createReplayJobWithAudit,
  type DestinationRow,
  type DisableProcessorActivationInput,
  deisolateTopicWithAudit,
  disableDestinationWithAudit,
  disableProcessorActivationWithAudit,
  type EnableProcessorActivationInput,
  enableDestinationWithAudit,
  enableProcessorActivationWithAudit,
  type FailReplayJobInput,
  fetchAllProjects,
  fetchAllSources,
  fetchSourcesById,
  fetchSourcesByProject,
  findActivationByKey,
  findActiveIsolation,
  findApiKeyById,
  findAuditRecordById,
  findClickhouseRebuildJobById,
  findDestinationById,
  findLatestIsolationByTriple,
  findOperatorTokenAuthRowById,
  findOperatorTokenById,
  findProcessorRunById,
  findReplayJobById,
  findTopicIsolationById,
  type InsertApiKeyInput,
  type InsertClickhouseRebuildJobInput,
  type InsertDestinationInput,
  type InsertOperatorTokenInput,
  type InsertReplayJobInput,
  type InsertTopicIsolationInput,
  type InvalidateProjectConfigInput,
  invalidateProjectConfigWithAudit,
  isAbortableClickhouseRebuildStatus,
  isolateTopicWithAudit,
  isTerminalClickhouseRebuildStatus,
  isTerminalReplayStatus,
  type ListAuditRecordsFilter,
  type ListClickhouseRebuildJobsFilter,
  type ListProjectConfigInput,
  type ListReplayJobsFilter,
  listActivationsForProcessor,
  listActiveIsolations,
  listAllActivations,
  listAllDestinations,
  listApiKeysByProjectEnv,
  listAuditRecords,
  listClickhouseRebuildJobs,
  listDestinationsByProjectEnv,
  listOperatorTokens,
  listProcessorRuns,
  listProjectConfig,
  listReplayJobs,
  type MarkReplayJobRunningInput,
  type MutationOutcome,
  markDlqResolvedWithAudit,
  markProcessorDlqResolvedWithAudit,
  markProcessorDlqRetriedWithAudit,
  OPERATOR_TOKEN_STATUSES,
  type OperatorTokenAuthRow,
  type OperatorTokenRow,
  type OperatorTokenStatus,
  type OperatorTokensTable,
  PlaintextSecretError,
  type ProcessorActivationKey,
  type ProcessorActivationRow,
  type ProcessorRunRow,
  type ProcessorRunScope,
  type ProjectConfigAuditSnapshot,
  type ProjectConfigRow,
  type ProjectConfigValueRef,
  type ProjectFile,
  type ProjectRow,
  pauseReplayJobWithAudit,
  pruneAttributionChainsWithAudit,
  REPLAY_JOB_MODES,
  REPLAY_JOB_STATUSES,
  REPLAY_JOB_TARGETS,
  type RecordReplayChunkProgressInput,
  type ReplayJobMode,
  type ReplayJobRow,
  type ReplayJobStatus,
  type ReplayJobsTable,
  type ReplayJobTarget,
  readProjectConfigVersion,
  resumeReplayJobWithAudit,
  revokeApiKeyWithAudit,
  revokeOperatorTokenWithAudit,
  rotateApiKeyWithAudit,
  type SetProjectConfigInput,
  type SourceFile,
  type SourceRow,
  setDestinationReplayOptInWithAudit,
  setProjectConfigValueWithAudit,
  startClickhouseRebuildWithAudit,
  startReplayExecutionWithAudit,
  syncProjectsWithAudit,
  syncSourcesWithAudit,
  TERMINAL_CLICKHOUSE_REBUILD_JOB_STATUSES,
  TERMINAL_REPLAY_JOB_STATUSES,
  type TopicIsolationRow,
  type UnsetProjectConfigInput,
  type UpdateDestinationOpsInput,
  unsetProjectConfigValueWithAudit,
  updateDestinationOpsWithAudit,
} from "@polaris/shared-control-plane-db";

// ---- executor progress --------------------------------------------------
// NOT operator actions: a running job reporting where it got to. They carry
// no audit row and never should — the decision that started the job was
// recorded when it started. See the package's progress.ts.
export {
  completeReplayJob,
  failReplayJob,
  markClickhouseRebuildJobCompleted,
  markClickhouseRebuildJobFailed,
  markClickhouseRebuildJobRunning,
  recordReplayChunkProgress,
  touchOperatorTokenLastUsedAt,
} from "@polaris/shared-control-plane-db/progress";

// ---- CLI-local ----------------------------------------------------------
export { type ConnectDbOptions, connectDb, type DbHandle } from "./connect.js";
export { createKyselyScopedIsolationLookup } from "./topic-isolations.js";
