/**
 * Internal DB surface for the CLI. Re-exported through a small index so the
 * command layer never reaches into `./db/*` directly.
 */
export {
  type ApiKeyRow,
  findApiKeyById,
  insertApiKey,
  type InsertApiKeyInput,
  listApiKeysByProjectEnv,
  revokeApiKey,
} from "./api-keys.js";
export {
  AUDIT_ACTOR_SOURCES,
  AUDIT_ENVIRONMENTS,
  type AuditActorSource,
  type AuditEnvironment,
  type AuditRecordRow,
  type AuditRecordsTable,
  findAuditRecordById,
  insertAuditRecord,
  type InsertAuditRecordInput,
  listAuditRecords,
  type ListAuditRecordsFilter,
} from "./audit-records.js";
export { type ConnectDbOptions, type DbHandle, connectDb } from "./connect.js";
export {
  disableDestination,
  disableDestinationReplay,
  enableDestination,
  enableDestinationReplay,
  type DestinationRow,
  findDestinationById,
  insertDestination,
  type InsertDestinationInput,
  listAllDestinations,
  listDestinationsByProjectEnv,
  updateDestinationOps,
  type UpdateDestinationOpsInput,
} from "./destinations.js";
export {
  disableProcessorActivation,
  type DisableProcessorActivationInput,
  enableProcessorActivation,
  type EnableProcessorActivationInput,
  findActivationByKey,
  listActivationsForProcessor,
  listAllActivations,
  type ProcessorActivationKey,
  type ProcessorActivationRow,
} from "./processor-activations.js";
export {
  findOperatorTokenAuthRowById,
  findOperatorTokenById,
  insertOperatorToken,
  type InsertOperatorTokenInput,
  listOperatorTokens,
  OPERATOR_TOKEN_STATUSES,
  type OperatorTokenAuthRow,
  type OperatorTokenRow,
  type OperatorTokenStatus,
  type OperatorTokensTable,
  revokeOperatorToken,
  touchOperatorTokenLastUsedAt,
} from "./operator-tokens.js";
export {
  fetchAllProjects,
  fetchAllSources,
  fetchSourcesById,
  fetchSourcesByProject,
  insertProject,
  insertSource,
  updateProject,
  updateSource,
} from "./projects.js";
export {
  cancelReplayJob,
  completeReplayJob,
  type CompleteReplayJobInput,
  failReplayJob,
  type FailReplayJobInput,
  findReplayJobById,
  insertReplayJob,
  type InsertReplayJobInput,
  isTerminalReplayStatus,
  listReplayJobs,
  type ListReplayJobsFilter,
  markReplayJobRunning,
  type MarkReplayJobRunningInput,
  pauseReplayJob,
  recordReplayChunkProgress,
  type RecordReplayChunkProgressInput,
  REPLAY_JOB_MODES,
  REPLAY_JOB_STATUSES,
  REPLAY_JOB_TARGETS,
  type ReplayJobMode,
  type ReplayJobRow,
  type ReplayJobsTable,
  type ReplayJobStatus,
  type ReplayJobTarget,
  resumeReplayJob,
  TERMINAL_REPLAY_JOB_STATUSES,
} from "./replay-jobs.js";
export {
  createKyselyScopedIsolationLookup,
  deactivateIsolation,
  findActiveIsolation,
  findLatestIsolationByTriple,
  findTopicIsolationById,
  insertTopicIsolation,
  type InsertTopicIsolationInput,
  listActiveIsolations,
  type TopicIsolationRow,
} from "./topic-isolations.js";
