// GENERATED by scripts/project-config-schemas-generate.mjs — do not edit.
//
// Regenerate with `pnpm config-schemas`; `pnpm config-schemas:check` and the
// scripts test suite fail when this file drifts from the component schemas.

/** A JSON Schema document as produced by zod v4's `z.toJSONSchema`. */
export type JsonSchema = Record<string, unknown>;

/** The generated schema surface for one component namespace. */
export interface ProjectConfigSchemaEntry {
  project: JsonSchema;
  instance?: JsonSchema;
  secretKeys: {
    project: string[];
    instance: string[];
  };
}

/**
 * Project-config schema artifacts, keyed by component namespace.
 *
 * Generated from each participating component's exported Zod schemas;
 * secret-typed keys carry `secret: true` and are listed in `secretKeys`.
 * Empty until the first per-service cutover (sessionizer) lands.
 */
export const PROJECT_CONFIG_SCHEMAS: Record<string, ProjectConfigSchemaEntry> = {
  ingest: {
    project: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      properties: {
        dedupe_window_sec: {
          maximum: 9007199254740991,
          minimum: 1,
          type: "integer",
        },
        rate_limit_rps: {
          maximum: 9007199254740991,
          minimum: 1,
          type: "integer",
        },
      },
      type: "object",
    },
    secretKeys: {
      project: [],
      instance: [],
    },
  },
};
