/**
 * CI drift and contract tests for the project-config schema-artifact
 * generator.
 *
 * The checked-in `packages/project-config-schemas` is the generated surface
 * the control plane imports. Test 1 re-runs the generator's pure core
 * in-process and compares byte-for-byte — a mismatch means a component schema
 * (or the generator) changed but the artifacts were not regenerated; the fix
 * is to run `pnpm config-schemas` and commit the result. The remaining tests
 * pin the artifact contract (shape, secret marking, additive-only compat
 * rules, determinism) against fixture Zod schemas — no fixture package, no
 * builds.
 *
 * Part of `pnpm test:scripts`, mirroring `openapi-generate.test.ts`.
 */

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { describe, expect, it } from "vitest";
import { z } from "zod";

// Re-use the script's pure core rather than re-implementing generation here —
// the goal is to detect drift in the *same* pipeline producers actually run.
import { buildArtifacts, checkCompat, REGISTRY } from "../project-config-schemas-generate.mjs";
import {
  compatAdditiveSchema,
  compatBaseSchema,
  compatPromotionSchema,
  compatRemovalSchema,
  compatTypeChangeSchema,
  FIXTURE_NAMESPACE,
  fixtureInstanceSchema,
  fixtureProjectSchema,
} from "./fixtures/project-config-schemas.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, "..", "..");
const PACKAGE_DIR = resolve(REPO_ROOT, "packages", "project-config-schemas");

const GENERATED_HEADER = "GENERATED by scripts/project-config-schemas-generate.mjs — do not edit.";

const fullFixtureEntry = {
  namespace: FIXTURE_NAMESPACE,
  projectSchema: fixtureProjectSchema,
  instanceSchema: fixtureInstanceSchema,
};

describe("project-config-schemas-generate", () => {
  it("regenerates byte-identical content to the checked-in package", async () => {
    // Loads each registry entry's BUILT dist, the same way the generator does,
    // so this asserts the committed artifacts match the live component schemas
    // rather than a hand-maintained copy of them. Requires `pnpm build` first;
    // CI builds before testing, and a missing dist fails loudly here rather
    // than silently reducing coverage to the empty-registry case.
    const entries = await Promise.all(
      REGISTRY.map(async (item) => {
        const distPath = resolve(REPO_ROOT, item.distEntry);
        if (!existsSync(distPath)) {
          throw new Error(
            `${item.distEntry} is missing — run \`pnpm config-schemas\` (it builds each entry) ` +
              "before this test, or run `pnpm build`.",
          );
        }
        const mod: Record<string, unknown> = await import(pathToFileURL(distPath).href);
        return {
          namespace: item.namespace,
          projectSchema: mod["projectConfigSchema"],
          ...(mod["instanceConfigSchema"] !== undefined
            ? { instanceSchema: mod["instanceConfigSchema"] }
            : {}),
        };
      }),
    );
    const files = buildArtifacts(entries) as Record<string, string>;
    expect(Object.keys(files).sort()).toEqual(listGeneratedFilesOnDisk());
    for (const [relPath, contents] of Object.entries(files)) {
      const committed = readFileSync(resolve(PACKAGE_DIR, relPath), "utf8");
      if (committed !== contents) {
        throw new Error(
          [
            `packages/project-config-schemas/${relPath} is out of date.`,
            "Re-run `pnpm config-schemas` and commit the result.",
            "",
            diffPreview(committed, contents),
          ].join("\n"),
        );
      }
      expect(committed).toBe(contents);
    }
  });

  it("produces both artifacts, valid JSON Schema, for a project+instance entry", () => {
    const files = buildArtifacts([fullFixtureEntry]) as Record<string, string>;
    expect(Object.keys(files).sort()).toEqual([
      `schemas/${FIXTURE_NAMESPACE}.instance.schema.json`,
      `schemas/${FIXTURE_NAMESPACE}.project.schema.json`,
      "src/index.ts",
    ]);
    const project = JSON.parse(fileOf(files, `schemas/${FIXTURE_NAMESPACE}.project.schema.json`));
    const instance = JSON.parse(fileOf(files, `schemas/${FIXTURE_NAMESPACE}.instance.schema.json`));
    for (const artifact of [project, instance]) {
      expect(artifact.type).toBe("object");
      expect(artifact.$schema).toContain("json-schema.org");
      expect(artifact.$comment).toBe(GENERATED_HEADER);
      expect(artifact.properties).toBeTypeOf("object");
    }
    // `io: "input"` semantics: only keys without a default are required, and
    // enum keys carry their values through the round trip (plan §3.1).
    expect(project.required).toEqual(["api_key"]);
    expect(project.properties.action_source.enum).toEqual(["website", "app", "physical_store"]);
    expect(instance.required).toEqual(["access_token", "pixel_id"]);
  });

  it("marks `.meta({ secret: true })` keys in the artifact and the index's secretKeys", () => {
    const files = buildArtifacts([fullFixtureEntry]) as Record<string, string>;
    const project = JSON.parse(fileOf(files, `schemas/${FIXTURE_NAMESPACE}.project.schema.json`));
    const instance = JSON.parse(fileOf(files, `schemas/${FIXTURE_NAMESPACE}.instance.schema.json`));
    expect(project.properties.api_key.secret).toBe(true);
    expect(project.properties.graph_host.secret).toBeUndefined();
    expect(instance.properties.access_token.secret).toBe(true);
    const index = fileOf(files, "src/index.ts");
    expect(index).toContain(`"${FIXTURE_NAMESPACE}": {`);
    expect(index).toContain('project: ["api_key"],');
    expect(index).toContain('instance: ["access_token"],');
  });

  it("compat: fails on property removal, naming the key", () => {
    const violations = checkCompat(
      projectArtifact(compatBaseSchema),
      projectArtifact(compatRemovalSchema),
    );
    expect(violations).toHaveLength(1);
    expect(violations[0]).toMatchObject({ key: "keep_me", rule: "removed" });
    expect(violations[0]?.message).toContain("keep_me");
  });

  it("compat: still fails on removal when the namespace has no exception", () => {
    // Passing a namespace must not weaken the rule — only a namespace WITH a
    // recorded exception for that exact key is allowed through.
    const violations = checkCompat(
      projectArtifact(compatBaseSchema),
      projectArtifact(compatRemovalSchema),
      "some-other-namespace",
    );
    expect(violations).toHaveLength(1);
    expect(violations[0]).toMatchObject({ key: "keep_me", rule: "removed" });
  });

  it("compat: allows the one recorded removal, and only for its own namespace", () => {
    // `meta-capi::allow_replay` is the single entry in REMOVAL_EXCEPTIONS: a
    // key that was declared and read by nothing, so a stored value never had
    // an effect to drop. Asserted against the real map rather than a fixture,
    // because an entry silently disappearing would put the removal back in
    // breach without any test noticing.
    const base = projectArtifact(
      z.object({ allow_replay: z.boolean().optional(), graph_host: z.string().optional() }),
    );
    const next = projectArtifact(z.object({ graph_host: z.string().optional() }));

    expect(checkCompat(base, next, "meta-capi")).toEqual([]);
    // The same removal in any other namespace is still a breaking change.
    expect(checkCompat(base, next, "ga4")).toHaveLength(1);
  });

  it("compat: fails on a property type change", () => {
    const violations = checkCompat(
      projectArtifact(compatBaseSchema),
      projectArtifact(compatTypeChangeSchema),
    );
    expect(violations).toHaveLength(1);
    expect(violations[0]).toMatchObject({ key: "typed_key", rule: "type-changed" });
  });

  it("compat: fails on optional -> required without a default", () => {
    const violations = checkCompat(
      projectArtifact(compatBaseSchema),
      projectArtifact(compatPromotionSchema),
    );
    expect(violations).toHaveLength(1);
    expect(violations[0]).toMatchObject({ key: "promote_me", rule: "required-without-default" });
  });

  it("compat: passes on additive change (new optional and defaulted keys)", () => {
    const violations = checkCompat(
      projectArtifact(compatBaseSchema),
      projectArtifact(compatAdditiveSchema),
    );
    expect(violations).toEqual([]);
  });

  it("produces identical bytes across two runs", () => {
    const a = buildArtifacts([fullFixtureEntry]) as Record<string, string>;
    const b = buildArtifacts([fullFixtureEntry]) as Record<string, string>;
    expect(b).toEqual(a);
  });
});

/** The generated-class files currently checked in, package-relative. */
function listGeneratedFilesOnDisk(): string[] {
  const out = ["src/index.ts"];
  const schemasDir = resolve(PACKAGE_DIR, "schemas");
  if (existsSync(schemasDir)) {
    for (const name of readdirSync(schemasDir)) {
      if (name.endsWith(".schema.json")) out.push(`schemas/${name}`);
    }
  }
  return out.sort();
}

/** The parsed project artifact the pure core generates for one schema. */
function projectArtifact(schema: unknown) {
  const files = buildArtifacts([{ namespace: "fixture-compat", projectSchema: schema }]) as Record<
    string,
    string
  >;
  return JSON.parse(fileOf(files, "schemas/fixture-compat.project.schema.json"));
}

function fileOf(files: Record<string, string>, relPath: string): string {
  const contents = files[relPath];
  if (contents === undefined) throw new Error(`generator did not emit ${relPath}`);
  return contents;
}

/**
 * Show a small diff window around the first mismatched line. Avoids
 * importing a diff library — the script test surface is intentionally
 * dependency-light.
 */
function diffPreview(expected: string, actual: string): string {
  const expectedLines = expected.split("\n");
  const actualLines = actual.split("\n");
  const max = Math.max(expectedLines.length, actualLines.length);
  for (let i = 0; i < max; i += 1) {
    if (expectedLines[i] !== actualLines[i]) {
      const window = (lines: string[], header: string): string => {
        const start = Math.max(0, i - 2);
        const end = Math.min(lines.length, i + 3);
        const chunk = lines
          .slice(start, end)
          .map((line, idx) => `  ${start + idx + 1}: ${line}`)
          .join("\n");
        return `${header}\n${chunk}`;
      };
      return [
        window(expectedLines, "expected (committed):"),
        window(actualLines, "actual (regenerated):"),
      ].join("\n");
    }
  }
  return "(no textual diff; lengths differ?)";
}
