// GENERATED by scripts/project-config-schemas-generate.mjs — do not edit.
//
// Regenerate with `pnpm config-schemas`; `pnpm config-schemas:check` and the
// scripts test suite fail when this file drifts from the component schemas.

/** A JSON Schema document as produced by zod v4's `z.toJSONSchema`. */
export type JsonSchema = Record<string, unknown>;

/** The generated schema surface for one component namespace. */
export interface ProjectConfigSchemaEntry {
  project: JsonSchema;
  instance?: JsonSchema;
  secretKeys: {
    project: string[];
    instance: string[];
  };
}

/**
 * Project-config schema artifacts, keyed by component namespace.
 *
 * Generated from each participating component's exported Zod schemas;
 * secret-typed keys carry `secret: true` and are listed in `secretKeys`.
 * One entry per component that has cut over to project configuration;
 * empty before the first cutover lands.
 */
export const PROJECT_CONFIG_SCHEMAS: Record<string, ProjectConfigSchemaEntry> = {
  braze: {
    project: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      properties: {
        api_host: {
          minLength: 1,
          type: "string",
        },
        request_timeout_ms: {
          maximum: 9007199254740991,
          minimum: 1,
          type: "integer",
        },
        routing: {
          additionalProperties: {},
          propertyNames: {
            type: "string",
          },
          type: "object",
        },
      },
      type: "object",
    },
    secretKeys: {
      project: [],
      instance: [],
    },
  },
  ga4: {
    project: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      properties: {
        api_host: {
          minLength: 1,
          type: "string",
        },
        request_timeout_ms: {
          maximum: 9007199254740991,
          minimum: 1,
          type: "integer",
        },
        routing: {
          additionalProperties: {},
          propertyNames: {
            type: "string",
          },
          type: "object",
        },
      },
      type: "object",
    },
    secretKeys: {
      project: [],
      instance: [],
    },
  },
  ingest: {
    project: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      properties: {
        dedupe_window_sec: {
          maximum: 9007199254740991,
          minimum: 1,
          type: "integer",
        },
        rate_limit_rps: {
          maximum: 9007199254740991,
          minimum: 1,
          type: "integer",
        },
      },
      type: "object",
    },
    secretKeys: {
      project: [],
      instance: [],
    },
  },
  "meta-capi": {
    project: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      properties: {
        graph_host: {
          minLength: 1,
          type: "string",
        },
        request_timeout_ms: {
          maximum: 9007199254740991,
          minimum: 1,
          type: "integer",
        },
        routing: {
          additionalProperties: {},
          propertyNames: {
            type: "string",
          },
          type: "object",
        },
      },
      type: "object",
    },
    secretKeys: {
      project: [],
      instance: [],
    },
  },
  reverse_etl: {
    project: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      properties: {
        enabled_jobs: {
          items: {
            pattern: "^[a-z][a-z0-9_]*$",
            type: "string",
          },
          type: "array",
        },
      },
      type: "object",
    },
    secretKeys: {
      project: [],
      instance: [],
    },
  },
  tiktok: {
    project: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      properties: {
        api_host: {
          minLength: 1,
          type: "string",
        },
        request_timeout_ms: {
          maximum: 9007199254740991,
          minimum: 1,
          type: "integer",
        },
        routing: {
          additionalProperties: {},
          propertyNames: {
            type: "string",
          },
          type: "object",
        },
      },
      type: "object",
    },
    secretKeys: {
      project: [],
      instance: [],
    },
  },
  "webhook-sink": {
    project: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      properties: {
        request_timeout_ms: {
          maximum: 9007199254740991,
          minimum: 1,
          type: "integer",
        },
        routing: {
          additionalProperties: {},
          propertyNames: {
            type: "string",
          },
          type: "object",
        },
      },
      type: "object",
    },
    secretKeys: {
      project: [],
      instance: [],
    },
  },
};
